import type { IndustryLineTemplate } from "./types";

export const golfCourseLineTemplate: IndustryLineTemplate = {
  industryType: "golf_course",
  tags: [
    { name: "平日関心", description: "平日プランや空き枠への反応があるユーザー" },
    { name: "土日祝関心", description: "土日祝の空き枠やキャンセル枠への反応があるユーザー" },
    { name: "コンペ関心", description: "コンペ案内や幹事向け情報に反応したユーザー" },
    { name: "一人予約関心", description: "一人予約案内へのクリックやアンケート回答があるユーザー" },
    { name: "初心者向け情報", description: "初心者向けプランや案内に関心があるユーザー" },
    { name: "直前空き枠関心", description: "直前枠案内や空き枠リンクに反応したユーザー" },
    { name: "限定プラン関心", description: "限定料金やクーポンに反応したユーザー" },
    { name: "高反応", description: "配信やメニューへの反応が多いユーザー" },
    { name: "30日間反応なし", description: "LINE内で30日以上反応が確認できないユーザー" },
    { name: "90日間反応なし", description: "LINE内で90日以上反応が確認できないユーザー" },
  ],
  surveys: [
    {
      title: "ゴルフ場向け初期アンケート",
      questions: [
        { text: "よく利用したい曜日", options: ["平日", "土日祝", "どちらも"] },
        { text: "興味のある内容", options: ["通常プレー", "一人予約", "コンペ", "初心者向けプラン", "直前空き枠", "限定料金"] },
        { text: "受け取りたいお知らせ", options: ["平日限定プラン", "土日祝の空き枠", "コンペ情報", "イベント情報", "クーポン"] },
      ],
    },
  ],
  segments: [
    { name: "平日プラン関心層", ruleSummary: "平日関心タグ、または平日限定プランへのクリック" },
    { name: "土日祝プラン関心層", ruleSummary: "土日祝関心タグ、または週末枠案内へのクリック" },
    { name: "コンペ関心層", ruleSummary: "コンペ関心タグ、またはコンペ案内への反応" },
    { name: "一人予約関心層", ruleSummary: "一人予約関心タグ、または一人予約リンクへの反応" },
    { name: "初心者向け情報関心層", ruleSummary: "初心者向け情報タグ、または初心者向け配信への反応" },
    { name: "直前空き枠関心層", ruleSummary: "直前空き枠関心タグ、または空き枠リンクへのクリック" },
    { name: "高反応ユーザー", ruleSummary: "直近30日間のクリック・回答・メニュー選択が多いユーザー" },
    { name: "アンケート未回答", ruleSummary: "友だち追加済みで初期アンケートが未回答" },
    { name: "30日間反応なし", ruleSummary: "LINE内最終反応日から30日以上経過" },
    { name: "90日間反応なし", ruleSummary: "LINE内最終反応日から90日以上経過" },
  ],
  broadcastTemplates: [
    { title: "平日限定プラン", objective: "平日関心層への再反応促進", exampleMessage: "平日限定のおすすめプランを公式LINE限定でご案内します。" },
    { title: "土日祝キャンセル枠", objective: "週末枠への関心を予約リンククリックにつなげる", exampleMessage: "土日祝の空き枠情報を更新しました。気になる日程をチェックできます。" },
    { title: "直前空き枠案内", objective: "直前空き枠関心層のクリック促進", exampleMessage: "直近の空き枠情報をまとめました。空き状況はリンクから確認できます。" },
    { title: "コンペ幹事向け案内", objective: "コンペ関心層への施策提案", exampleMessage: "コンペ幹事さま向けの案内をお届けします。人数や希望時期に合わせてご確認ください。" },
    { title: "一人予約案内", objective: "一人予約関心層の反応獲得", exampleMessage: "一人予約に関心がある方向けの案内です。気軽に参加できる枠をご確認ください。" },
    { title: "初心者向けプラン", objective: "初心者向け情報関心層への案内", exampleMessage: "初心者の方にも使いやすいプランや持ち物情報をまとめました。" },
    { title: "季節イベント", objective: "イベント情報への反応確認", exampleMessage: "季節のイベント情報を公式LINEからお知らせします。" },
    { title: "期間限定クーポン", objective: "限定プラン関心層のクリック促進", exampleMessage: "期間限定のクーポンをご用意しました。詳細はリンクから確認できます。" },
  ],
  stepCampaignTemplates: [
    {
      title: "友だち追加後の基本ステップ",
      steps: [
        { timing: "友だち追加直後", message: "施設の特徴、空き枠確認方法、公式LINE限定情報を案内" },
        { timing: "3日後", message: "人気の配信テーマと直近空き枠の確認リンクを案内" },
        { timing: "7日後", message: "利用したい曜日や興味内容のアンケートを送信" },
        { timing: "14日後", message: "回答内容に合わせてプランやイベント情報を案内" },
        { timing: "30日後", message: "限定クーポンまたは直前空き枠情報を案内" },
      ],
    },
  ],
  friendActionPlans: [
    {
      friendType: "新規公式LINE追加者",
      conditionSummary: "友だち追加直後、まだアンケート回答やリンククリックがないユーザー",
      recommendedTiming: "追加直後から24時間以内",
      objective: "施設理解と初回アンケート回答を促す",
      messageTheme: "施設紹介 + 初期アンケート + 空き枠確認導線",
      exampleMessage: "友だち追加ありがとうございます。空き枠や限定プランを受け取りやすくするため、よく利用したい曜日を教えてください。",
      primaryAction: "初期アンケートを送信",
      relatedTags: ["アンケート未回答", "初心者向け情報"],
    },
    {
      friendType: "アンケート未回答",
      conditionSummary: "友だち追加後、初期アンケートが未回答のユーザー",
      recommendedTiming: "追加から3日後",
      objective: "関心タグ付けに必要な回答を集める",
      messageTheme: "回答メリット + 1分アンケート",
      exampleMessage: "ご希望に近いプランをお届けするため、1分だけアンケートにご協力ください。平日・土日祝・コンペなど興味に合わせてご案内します。",
      primaryAction: "アンケート再送",
      relatedTags: ["アンケート未回答"],
    },
    {
      friendType: "平日プラン関心層",
      conditionSummary: "平日関心タグ、または平日限定プランへのクリックがあるユーザー",
      recommendedTiming: "平日枠を出した当日または前日",
      objective: "平日空き枠リンクのクリックを増やす",
      messageTheme: "平日限定プラン + 空き枠確認",
      exampleMessage: "平日限定のおすすめ枠を更新しました。混み合いにくい時間帯を中心に、空き状況をLINEから確認できます。",
      primaryAction: "空き枠リンクへ誘導",
      relatedTags: ["平日関心", "限定プラン関心"],
    },
    {
      friendType: "コンペ関心層",
      conditionSummary: "コンペ関心タグ、コンペ案内クリック、幹事向け情報への反応があるユーザー",
      recommendedTiming: "月初またはイベント告知前",
      objective: "幹事向け相談・問い合わせを増やす",
      messageTheme: "コンペ幹事向け案内 + 特典",
      exampleMessage: "コンペをご検討中の方向けに、幹事さまが確認しやすい案内をまとめました。人数や希望時期に合わせてご相談いただけます。",
      primaryAction: "コンペ相談リンクへ誘導",
      relatedTags: ["コンペ関心", "高反応"],
    },
    {
      friendType: "高反応ユーザー",
      conditionSummary: "直近30日で複数回クリック・回答・リッチメニュー選択があるユーザー",
      recommendedTiming: "限定プラン公開直後",
      objective: "反応が高いテーマへのクリックを伸ばす",
      messageTheme: "先行案内 + 限定クーポン",
      exampleMessage: "いつもLINEをご覧いただきありがとうございます。反応の多い方向けに、期間限定の案内を先にお届けします。",
      primaryAction: "限定プラン配信",
      relatedTags: ["高反応", "限定プラン関心"],
    },
    {
      friendType: "30日間反応なし",
      conditionSummary: "LINE内の最終反応から30日以上経過しているユーザー",
      recommendedTiming: "月1回まで",
      objective: "ブロックを増やさず再反応を作る",
      messageTheme: "軽い近況案内 + 人気リンク1つ",
      exampleMessage: "最近よく見られている空き枠情報を1つだけお届けします。気になるタイミングがあればLINEから確認できます。",
      primaryAction: "人気リンクを1つだけ配信",
      relatedTags: ["30日間反応なし"],
    },
    {
      friendType: "90日間反応なし",
      conditionSummary: "LINE内の最終反応から90日以上経過しているユーザー",
      recommendedTiming: "四半期に1回程度",
      objective: "配信頻度を抑えて反応有無を確認する",
      messageTheme: "配信希望確認 + クーポン",
      exampleMessage: "今後受け取りたい情報を選べます。平日プラン、イベント、クーポンなど、必要な情報だけお届けします。",
      primaryAction: "受信希望アンケートを送信",
      relatedTags: ["90日間反応なし"],
    },
  ],
  dashboardLabels: {
    industryLabel: "ゴルフ場",
    assistMetrics: ["平日プラン関心層", "コンペ関心層", "一人予約関心層", "直前空き枠関心層"],
    richMenuExamples: ["空き枠確認", "一人予約", "コンペ相談", "クーポン", "イベント情報"],
    recommendedActions: [
      {
        title: "コンペ案内への関心が高まっています",
        body: "直近30日間で「コンペ案内」のクリック数が増加しています。コンペ関心タグを持つユーザーへ、幹事特典付きの案内を配信することをおすすめします。",
        targetLabel: "コンペ関心層",
      },
      {
        title: "直前空き枠への再反応を狙えます",
        body: "直前空き枠リンクへの反応が続いています。週末前に空き枠確認リンク付きの配信を準備してください。",
        targetLabel: "直前空き枠関心層",
      },
    ],
    contentWords: {
      planInterest: "プレープランへの関心",
      linkReaction: "空き枠リンククリック数",
      inactiveUser: "LINE内で反応がないユーザー",
    },
  },
  aiPromptContext: "ゴルフ場の実来場、予約完了、売上を断定せず、LINE内のクリック、アンケート回答、リッチメニュー選択、配信反応だけを根拠に提案する。",
  aiSuggestionExamples: [
    "直近30日間で「コンペ案内」のクリック数が増加しています。コンペ関心タグを持つユーザーへ、幹事特典付きの案内を配信することをおすすめします。",
  ],
};
