import type { IndustryLineTemplate } from "./types";

export const hotelLineTemplate: IndustryLineTemplate = {
  industryType: "hotel",
  tags: [
    { name: "平日宿泊関心", description: "平日限定プランや空室情報への反応があるユーザー" },
    { name: "週末宿泊関心", description: "週末プランや週末空室情報への反応があるユーザー" },
    { name: "ビジネス利用", description: "ビジネス利用を示すアンケート回答や配信反応があるユーザー" },
    { name: "観光利用", description: "観光目的のアンケート回答や観光情報への反応があるユーザー" },
    { name: "家族旅行", description: "家族旅行関連の配信やアンケート回答に反応したユーザー" },
    { name: "カップル利用", description: "カップル向けプランやアンケート回答に反応したユーザー" },
    { name: "連泊関心", description: "連泊プランへのクリックや回答があるユーザー" },
    { name: "朝食関心", description: "朝食付きプランや館内案内への反応があるユーザー" },
    { name: "館内施設関心", description: "館内サービスや施設案内への反応があるユーザー" },
    { name: "周辺観光関心", description: "周辺観光情報やイベント案内への反応があるユーザー" },
    { name: "限定プラン関心", description: "限定宿泊プランやクーポンに反応したユーザー" },
    { name: "高反応", description: "配信やメニューへの反応が多いユーザー" },
    { name: "30日間反応なし", description: "LINE内で30日以上反応が確認できないユーザー" },
    { name: "90日間反応なし", description: "LINE内で90日以上反応が確認できないユーザー" },
  ],
  surveys: [
    {
      title: "ホテル向け初期アンケート",
      questions: [
        { text: "主なご利用目的", options: ["ビジネス", "観光", "家族旅行", "カップル旅行", "その他"] },
        { text: "興味のある内容", options: ["平日限定プラン", "週末プラン", "連泊プラン", "朝食付きプラン", "季節限定プラン", "周辺観光情報", "館内サービス"] },
        { text: "受け取りたいお知らせ", options: ["空室情報", "限定宿泊プラン", "クーポン", "周辺イベント", "館内からのお知らせ"] },
      ],
    },
  ],
  segments: [
    { name: "ビジネス利用関心層", ruleSummary: "ビジネス利用タグ、またはビジネス向け配信への反応" },
    { name: "観光利用関心層", ruleSummary: "観光利用タグ、または観光情報へのクリック" },
    { name: "家族旅行関心層", ruleSummary: "家族旅行タグ、または家族向けプランへの反応" },
    { name: "カップル利用関心層", ruleSummary: "カップル利用タグ、またはカップル向け案内への反応" },
    { name: "平日宿泊関心層", ruleSummary: "平日宿泊関心タグ、または平日限定プランへのクリック" },
    { name: "週末宿泊関心層", ruleSummary: "週末宿泊関心タグ、または週末空室情報へのクリック" },
    { name: "連泊プラン関心層", ruleSummary: "連泊関心タグ、または連泊プランへの反応" },
    { name: "朝食付きプラン関心層", ruleSummary: "朝食関心タグ、または朝食付きプランへのクリック" },
    { name: "周辺観光情報関心層", ruleSummary: "周辺観光関心タグ、または周辺イベント案内への反応" },
    { name: "高反応ユーザー", ruleSummary: "直近30日間のクリック・回答・メニュー選択が多いユーザー" },
    { name: "アンケート未回答", ruleSummary: "友だち追加済みで初期アンケートが未回答" },
    { name: "30日間反応なし", ruleSummary: "LINE内最終反応日から30日以上経過" },
    { name: "90日間反応なし", ruleSummary: "LINE内最終反応日から90日以上経過" },
  ],
  broadcastTemplates: [
    { title: "平日限定宿泊プラン", objective: "平日宿泊関心層のクリック促進", exampleMessage: "平日限定の宿泊プラン情報を公式LINEからご案内します。" },
    { title: "週末空室情報", objective: "週末宿泊関心層への空室情報反応獲得", exampleMessage: "週末の空室情報を更新しました。詳細は予約リンクから確認できます。" },
    { title: "直前割プラン", objective: "空室情報への反応があるユーザーの再反応促進", exampleMessage: "直前割プランの情報をお届けします。対象期間はリンクからご確認ください。" },
    { title: "連泊特典", objective: "連泊プラン関心層への提案", exampleMessage: "連泊をご検討中の方向けに、特典付きプランをご案内します。" },
    { title: "朝食付きプラン", objective: "朝食関心層への案内", exampleMessage: "朝食付きプランのおすすめ情報をまとめました。" },
    { title: "季節限定プラン", objective: "限定プラン関心層のクリック促進", exampleMessage: "季節限定プランを公式LINEで先にお知らせします。" },
    { title: "周辺イベント案内", objective: "観光・周辺情報への反応確認", exampleMessage: "周辺イベント情報をまとめました。滞在計画の参考にご覧ください。" },
    { title: "観光モデルコース", objective: "観光利用関心層への回遊促進", exampleMessage: "観光目的の方向けにモデルコースをご紹介します。" },
    { title: "館内サービス案内", objective: "館内施設関心層への案内", exampleMessage: "館内サービスの最新情報をお届けします。" },
    { title: "期間限定クーポン", objective: "限定プラン関心層の再反応促進", exampleMessage: "公式LINE限定クーポンをご用意しました。詳細をご確認ください。" },
  ],
  stepCampaignTemplates: [
    {
      title: "ホテル向け友だち追加後ステップ",
      steps: [
        { timing: "友だち追加直後", message: "ホテルの特徴、予約方法、公式LINE限定情報を案内" },
        { timing: "3日後", message: "人気宿泊プランを案内" },
        { timing: "7日後", message: "利用目的アンケートを送信" },
        { timing: "14日後", message: "回答内容に合わせてプランを案内" },
        { timing: "30日後", message: "限定クーポンまたは空室情報を案内" },
      ],
    },
  ],
  friendActionPlans: [
    {
      friendType: "新規公式LINE追加者",
      conditionSummary: "友だち追加直後、まだアンケート回答や予約リンククリックがないユーザー",
      recommendedTiming: "追加直後から24時間以内",
      objective: "ホテルの特徴理解と利用目的アンケート回答を促す",
      messageTheme: "ホテル紹介 + 公式LINE限定情報 + 利用目的アンケート",
      exampleMessage: "友だち追加ありがとうございます。ご希望に近い宿泊プランや空室情報をお届けするため、主なご利用目的を教えてください。",
      primaryAction: "利用目的アンケートを送信",
      relatedTags: ["アンケート未回答", "限定プラン関心"],
    },
    {
      friendType: "アンケート未回答",
      conditionSummary: "友だち追加後、初期アンケートが未回答のユーザー",
      recommendedTiming: "追加から3日後",
      objective: "ビジネス・観光・家族旅行などの関心分類を作る",
      messageTheme: "回答メリット + 1分アンケート",
      exampleMessage: "ビジネス、観光、家族旅行など、目的に合わせたお知らせを受け取れます。1分だけアンケートにご協力ください。",
      primaryAction: "アンケート再送",
      relatedTags: ["アンケート未回答"],
    },
    {
      friendType: "週末宿泊関心層",
      conditionSummary: "週末宿泊関心タグ、または週末プラン・空室情報へのクリックがあるユーザー",
      recommendedTiming: "木曜から金曜午前",
      objective: "週末空室情報への反応を増やす",
      messageTheme: "週末空室情報 + 限定宿泊プラン",
      exampleMessage: "週末の空室情報を更新しました。気軽な滞在や観光の拠点に使いやすいプランをLINEから確認できます。",
      primaryAction: "予約リンクへ誘導",
      relatedTags: ["週末宿泊関心", "限定プラン関心"],
    },
    {
      friendType: "ビジネス利用関心層",
      conditionSummary: "ビジネス利用タグ、または平日・連泊・朝食付きプランに反応があるユーザー",
      recommendedTiming: "月曜午前または平日前",
      objective: "平日・連泊・朝食付きプランへのクリックを増やす",
      messageTheme: "平日宿泊 + 朝食 + 連泊メリット",
      exampleMessage: "出張や平日利用に便利な宿泊プランをまとめました。朝食付きや連泊向けの情報もLINEから確認できます。",
      primaryAction: "平日宿泊プランへ誘導",
      relatedTags: ["ビジネス利用", "平日宿泊関心", "朝食関心", "連泊関心"],
    },
    {
      friendType: "観光利用関心層",
      conditionSummary: "観光利用タグ、周辺観光情報、周辺イベントへの反応があるユーザー",
      recommendedTiming: "週末前または季節イベント前",
      objective: "周辺観光情報から宿泊プランへの再反応を作る",
      messageTheme: "周辺イベント + 観光モデルコース + 宿泊プラン",
      exampleMessage: "周辺イベントと観光モデルコースをまとめました。気になる予定に合わせて、宿泊プランもLINEから確認できます。",
      primaryAction: "観光モデルコースへ誘導",
      relatedTags: ["観光利用", "周辺観光関心", "週末宿泊関心"],
    },
    {
      friendType: "高反応ユーザー",
      conditionSummary: "直近30日で複数回クリック・回答・リッチメニュー選択があるユーザー",
      recommendedTiming: "限定プラン公開直後",
      objective: "反応が高いテーマへのクリックを伸ばす",
      messageTheme: "先行案内 + 期間限定クーポン",
      exampleMessage: "いつもLINEをご覧いただきありがとうございます。反応の多い方向けに、期間限定の宿泊プランを先にお知らせします。",
      primaryAction: "限定宿泊プラン配信",
      relatedTags: ["高反応", "限定プラン関心"],
    },
    {
      friendType: "30日間反応なし",
      conditionSummary: "LINE内の最終反応から30日以上経過しているユーザー",
      recommendedTiming: "月1回まで",
      objective: "負担の少ない配信で再反応を作る",
      messageTheme: "人気宿泊テーマ + リンク1つ",
      exampleMessage: "最近よく見られている宿泊プランを1つだけお届けします。空室情報や詳細はLINEから確認できます。",
      primaryAction: "人気プランリンクを1つだけ配信",
      relatedTags: ["30日間反応なし"],
    },
    {
      friendType: "90日間反応なし",
      conditionSummary: "LINE内の最終反応から90日以上経過しているユーザー",
      recommendedTiming: "四半期に1回程度",
      objective: "配信希望テーマを確認し、不要な配信を減らす",
      messageTheme: "受け取りたい情報の確認 + クーポン",
      exampleMessage: "今後受け取りたいホテル情報を選べます。空室情報、限定宿泊プラン、周辺イベントなど、必要な情報だけお届けします。",
      primaryAction: "受信希望アンケートを送信",
      relatedTags: ["90日間反応なし"],
    },
  ],
  dashboardLabels: {
    industryLabel: "ホテル",
    assistMetrics: ["ビジネス利用関心層", "観光利用関心層", "週末宿泊関心層", "連泊プラン関心層"],
    richMenuExamples: ["空室情報", "宿泊プラン", "周辺観光", "館内サービス", "クーポン"],
    recommendedActions: [
      {
        title: "週末宿泊プランへの反応が高まっています",
        body: "週末宿泊プランへのクリック率が高い一方で、直近30日間は週末向け配信が行われていません。週末宿泊関心層へ、直近の空室情報または限定プランを配信することをおすすめします。",
        targetLabel: "週末宿泊関心層",
      },
      {
        title: "周辺観光情報から再反応を作れます",
        body: "周辺観光情報へのクリックが増えています。観光利用関心層に、季節イベントと宿泊プランへのリンクを組み合わせた配信をおすすめします。",
        targetLabel: "観光利用関心層",
      },
    ],
    contentWords: {
      planInterest: "宿泊プランへの関心",
      linkReaction: "予約リンククリック数",
      inactiveUser: "LINE内で反応がないユーザー",
    },
  },
  aiPromptContext: "ホテルの実宿泊回数、宿泊日、稼働率、客室売上、予約完了数を断定せず、LINE内のクリック、アンケート回答、空室情報への反応、配信クリック率だけを根拠に提案する。",
  aiSuggestionExamples: [
    "週末宿泊プランへのクリック率が高い一方で、直近30日間は週末向け配信が行われていません。週末宿泊関心層へ、直近の空室情報または限定プランを配信することをおすすめします。",
  ],
};
